users:
  uid: {
    userName: string,
    adminFlag: boolean,
    createdAt: timestamp,
    updatedAt: timestamp,
    history: {
      bookId: string,
      isbn: string,
      title: string,
      author: string,
      imageLink: string,
      checkoutDate: date,
      returnDate: date,
      storageLocation: string,
      createdAt: timestamp,
      updatedAt: timestamp,
    }
  }

books:
  id: {
    isbn: string,
    title: string,
    author: string,
    publisherName: string,
    publicationDate: date,
    purchaseDate: date,
    price: number,
    versionNumber: number,
    imageLink: string,
    storageLocation: string,
    lendingStatus: boolean,
    createdAt: timestamp,
    updatedAt: timestamp
  }

lending: {
  id: {
    uid: string,
    bookId: string,
    isbn: string,
    title: string,
    author: string,
    imageLink: string,
    checkoutDate: date,
    returnDate: date,
    storageLocation: string,
    createdAt: timestamp,
    updatedAt: timestamp
  }
}

storages: 
  id: {
    storageLocation: string,
  }
}