users:
  uid: {
  userName: string,
  adminFlag: boolean,
  createdAt: timestamp,
  updatedAt: timestamp
  }

books:
  id: {
    isbn: string,
    title: string,
    author: string,
    publicationDate: date,
    purchaseDate: date,
    price: number,
    versionNumber: number,
    imageLink: string,
    storageLocation: ref,
    createdAt: timestamp,
    updatedAt: timestamp
  }

storages:
  storageId: {
    storageLocation: string
  }

## セキュリティルール複雑化を避けるため非正規化を採用。historyには状態を持たせず、lendingに切り出す

lending: {
  id: {
    uid: string,
    isbn: string,
    checkoutDate: date,
    returnDate: date,
    createdAt: timestamp,
    updatedAt: timestamp
  }
}

history: {
  id: {
    uid: string,
    isbn: string,
    checkoutDate: date,
    returnDate: date,
    createdAt: timestamp,
  }
}